#!/usr/bin/env python3
"""Copy only device-side adb shell bodies into Rust constants. No host script is executed.
Run --check in tests; changes to classic scripts require reviewing the Rust control flow too.
"""
import argparse,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def commands(path):
 s=path.read_text();res={}
 for m in re.finditer(r'\badb shell\s+',s):
  i=m.end();start=i;quote=None;out=''
  while i<len(s):
   c=s[i]
   if quote is None and (c.isspace() or c in ';|)&<>'):break
   if c in "\"'" and quote is None:quote=c
   elif c==quote:quote=None
   elif c=='\\' and quote!="'" and i+1<len(s):
    n=s[i+1]
    if quote is None or n in '\\$`"\n':
     if n!='\n':out+=n
     i+=1
    else:out+=c
   else:out+=c
   i+=1
  if s[start:start+1] in "\"'":res[s.count('\n',0,m.start())+1]=out
 return res
SOURCES = ('device/install.sh', 'device/remove.sh')

def render():
 out='// Device commands ported verbatim from Packaging/od/installer.\n// Generated by scripts/sync-classic-commands.py; control flow lives in engine.rs.\n'
 seen=set()
 for source in SOURCES:
  path=ROOT/'Packaging/od/installer'/source
  lines=path.read_text().splitlines()
  found=commands(path)
  for index,line in enumerate(lines):
   marker=re.fullmatch(r'\s*# @installer-command ([A-Z_]+)\s*',line)
   if not marker:continue
   name=marker.group(1)
   if name in seen:raise ValueError(f'Duplicate command marker: {name}')
   seen.add(name)
   candidates=[number for number in found if index+1<number<=index+4]
   if not candidates:raise ValueError(f'No quoted adb shell command after {source}:{index+1} ({name})')
   number=min(candidates)
   out+=f'// Packaging/od/installer/{source}:{number}\npub const {name}: &str = r###"{found[number]}"###;\n'
 if not seen:raise ValueError('No installer command markers found')
 return out
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 target=ROOT/'Installer/crates/installer-core/src/classic_commands.rs';expected=render()
 if args.check:
  pattern=r'pub const (\w+): &str =\s*r###"(.*?)"###;'
  if dict(re.findall(pattern,target.read_text(),re.S))!=dict(re.findall(pattern,expected,re.S)):raise SystemExit('Classic ADB commands changed. Review the port and run sync-classic-commands.py.')
 else:target.write_text(expected)
