/*
 * Auto-generated by Frida. Please modify to match the signature of qg_canbus_control.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('qg_canbus_control()');
    log(args[0]);
    log(hexdump(args[1]));
  },

  onLeave(log, retval, state) {
  }
});
